"""
Output writer — persists schema agent results to disk.

Writes:
  output/schema.sql          DDL CREATE TABLE statements
  output/relationships.json  FK relationship map
  output/model.tmdl          TMDL semantic model skeleton
  output/review_checklist.md Consultant-facing review checklist
"""

from __future__ import annotations

import json
from pathlib import Path


def write_all(result: dict, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    _write_sql(result.get("ddl_statements", []), output_dir / "schema.sql")
    _write_relationships(result.get("relationships", []), output_dir / "relationships.json")
    _write_tmdl(result.get("tmdl_skeleton", ""), output_dir / "model.tmdl")
    _write_checklist(result.get("review_checklist", []), output_dir / "review_checklist.md")


def _write_sql(ddl_statements: list[str], path: Path) -> None:
    header = (
        "-- ============================================================\n"
        "-- BI-Stack POC — Schema Inference Agent Output\n"
        "-- Generated by: schema_agent.py\n"
        "-- Review before executing. Check review_checklist.md first.\n"
        "-- ============================================================\n\n"
        "USE BI_POC;\nGO\n\n"
    )
    body = "\nGO\n\n".join(ddl_statements) + "\nGO\n"
    path.write_text(header + body, encoding="utf-8")
    print(f"  Wrote {path.name}")


def _write_relationships(relationships: list[dict], path: Path) -> None:
    payload = {
        "schema_version": "1.0",
        "generated_by": "schema_agent",
        "relationships": relationships,
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"  Wrote {path.name}")


def _write_tmdl(tmdl_content: str, path: Path) -> None:
    path.write_text(tmdl_content, encoding="utf-8")
    print(f"  Wrote {path.name}")


def _write_checklist(items: list[dict], path: Path) -> None:
    SEVERITY_ICON = {"high": "🔴", "medium": "🟡", "low": "🟢", "info": "ℹ️"}

    lines = [
        "# Schema Review Checklist\n",
        "_Generated by schema_agent. Review before executing DDL or publishing the model._\n",
        "",
        "| # | Severity | Category | Item | Recommendation |",
        "|---|----------|----------|------|----------------|",
    ]

    for i, item in enumerate(items, start=1):
        sev  = item.get("severity", "info").lower()
        icon = SEVERITY_ICON.get(sev, "ℹ️")
        cat  = item.get("category", "")
        it   = item.get("item", "").replace("|", "\\|")
        rec  = item.get("recommendation", "").replace("|", "\\|")
        lines.append(f"| {i} | {icon} {sev.upper()} | {cat} | {it} | {rec} |")

    lines += [
        "",
        "---",
        "",
        "## Decision Log",
        "",
        "_Fill in as you review each item._\n",
    ]

    for i, item in enumerate(items, start=1):
        sev = item.get("severity", "info").lower()
        if sev in ("high", "medium"):
            lines.append(f"### Item {i} — {item.get('item', '')}")
            lines.append(f"- **Decision:** ")
            lines.append(f"- **Notes:** ")
            lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Wrote {path.name}")
